### ISSUE TITLE
Basic example fails to build on macOS

### ISSUE THREAD

**Issue by nchapman** [nchapman/nebula#6]
```
➜  nebula git:(main) cargo r --example basic
   Compiling llama-cpp-sys v0.0.1 (/Users/nchapman/Code/nebula/backends/llama_cpp/llama-cpp-sys)
error: failed to run custom build command for `llama-cpp-sys v0.0.1 (/Users/nchapman/Code/nebula/backends/llama_cpp/llama-cpp-sys)`

Caused by:
  process didn't exit successfully: `/Users/nchapman/Code/nebula/target/debug/build/llama-cpp-sys-f634e19f932fd4df/build-script-build` (exit status: 101)
  --- stdout
  cargo:rerun-if-changed=llama.cpp
  OPT_LEVEL = Some("0")
  TARGET = Some("aarch64-apple-darwin")
  HOST = Some("aarch64-apple-darwin")
  cargo:rerun-if-env-changed=CC_aarch64-apple-darwin
  CC_aarch64-apple-darwin = None
  cargo:rerun-if-env-changed=CC_aarch64_apple_darwin
  CC_aarch64_apple_darwin = None
  cargo:rerun-if-env-changed=HOST_CC
  HOST_CC = None
  cargo:rerun-if-env-changed=CC
  CC = None
  cargo:rerun-if-env-changed=CC_ENABLE_DEBUG_OUTPUT
  cargo:rerun-if-env-changed=CRATE_CC_NO_DEFAULTS
  CRATE_CC_NO_DEFAULTS = None
  DEBUG = Some("true")
  cargo:rerun-if-env-changed=CFLAGS_aarch64-apple-darwin
  CFLAGS_aarch64-apple-darwin = None
  cargo:rerun-if-env-changed=CFLAGS_aarch64_apple_darwin
  CFLAGS_aarch64_apple_darwin = None
  cargo:rerun-if-env-changed=HOST_CFLAGS
  HOST_CFLAGS = None
  cargo:rerun-if-env-changed=CFLAGS
  CFLAGS = None
  OPT_LEVEL = Some("0")
  TARGET = Some("aarch64-apple-darwin")
  HOST = Some("aarch64-apple-darwin")
  cargo:rerun-if-env-changed=CXX_aarch64-apple-darwin
  CXX_aarch64-apple-darwin = None
  cargo:rerun-if-env-changed=CXX_aarch64_apple_darwin
  CXX_aarch64_apple_darwin = None
  cargo:rerun-if-env-changed=HOST_CXX
  HOST_CXX = None
  cargo:rerun-if-env-changed=CXX
  CXX = None
  cargo:rerun-if-env-changed=CC_ENABLE_DEBUG_OUTPUT
  cargo:rerun-if-env-changed=CRATE_CC_NO_DEFAULTS
  CRATE_CC_NO_DEFAULTS = None
  DEBUG = Some("true")
  cargo:rerun-if-env-changed=CXXFLAGS_aarch64-apple-darwin
  CXXFLAGS_aarch64-apple-darwin = None
  cargo:rerun-if-env-changed=CXXFLAGS_aarch64_apple_darwin
  CXXFLAGS_aarch64_apple_darwin = None
  cargo:rerun-if-env-changed=HOST_CXXFLAGS
  HOST_CXXFLAGS = None
  cargo:rerun-if-env-changed=CXXFLAGS
  CXXFLAGS = None
  cargo:rustc-link-lib=framework=Metal
  cargo:rustc-link-lib=framework=Foundation
  cargo:rustc-link-lib=framework=MetalPerformanceShaders
  cargo:rustc-link-lib=framework=MetalKit
  cargo:rustc-link-arg=framework=Accelerate

  --- stderr
  thread 'main' panicked at backends/llama_cpp/llama-cpp-sys/build.rs:421:13:
  ggml-metal.m does not contain the needle to be replaced; the patching logic needs to be reinvestigated. Contact a `llama-cpp-sys-2` developer!
  note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

**Comment by iKachaykin** [comment]
@nchapman @Warefoxe I experience the same on my macOS as well btw. I think the issue is in the following:

`ggml-metal.m does not contain the needle to be replaced; the patching logic needs to be reinvestigated. Contact a llama-cpp-sys-2 developer!`

**Comment by nchapman** [comment]
@Warefoxe I'm now getting a new error:

```
   Compiling llama-cpp v0.0.1 (/Users/nchapman/Code/nebula/backends/llama_cpp/llama-cpp)
error[E0658]: use of unstable library feature 'ptr_from_ref'
   --> backends/llama_cpp/llama-cpp/src/token/data_array.rs:362:22
    |
362 |         let mu_ptr = ptr::from_mut(mu);
    |                      ^^^^^^^^^^^^^
    |
    = note: see issue #106116 <https://github.com/rust-lang/rust/issues/106116> for more information

For more information about this error, try `rustc --explain E0658`.
error: could not compile `llama-cpp` (lib) due to previous error
```

This one is strange because I would expect to get the same error on Windows (which I don't). 

@iKachaykin will you try building to see if it works for you?

**Comment by Warefoxe** [comment]
@nchapman, thanks for testing, can You share what version of rustc, rustup and cargo do You use?

**Comment by nchapman** [comment]
@Warefoxe Thanks for the suggestion. I realized I was using rust from homebrew on my mac. I reinstalled via rustup which fixed the above issue and now I have a new one for you 😄 .

```
rustup 1.27.0 (bbb9276d2 2024-03-08)
rustc 1.76.0 (07dca489a 2024-02-04)
```

```
➜  nebula git:(main) cargo r --release --example basic
warning: llama-cpp-sys@0.0.1: llama.cpp/ggml.c:2125:17: warning: unused function 'ggml_get_numa_affinity' [-Wunused-function]
warning: llama-cpp-sys@0.0.1: static uint32_t ggml_get_numa_affinity(void) {
warning: llama-cpp-sys@0.0.1:                 ^
warning: llama-cpp-sys@0.0.1: llama.cpp/ggml.c:2477:19: warning: unused function 'ggml_up32' [-Wunused-function]
warning: llama-cpp-sys@0.0.1: static inline int ggml_up32(int n) {
warning: llama-cpp-sys@0.0.1:                   ^
warning: llama-cpp-sys@0.0.1: llama.cpp/ggml.c:19277:13: warning: unused function 'ggml_opt_get_grad' [-Wunused-function]
warning: llama-cpp-sys@0.0.1: static void ggml_opt_get_grad(int np, struct ggml_tensor * const ps[], float * g) {
warning: llama-cpp-sys@0.0.1:             ^
warning: llama-cpp-sys@0.0.1: 3 warnings generated.
warning: llama-cpp-sys@0.0.1: llama.cpp/ggml-alloc.c:436:13: warning: unused function 'ggml_gallocr_set_node_offset' [-Wunused-function]
warning: llama-cpp-sys@0.0.1: static void ggml_gallocr_set_node_offset(ggml_gallocr_t galloc, struct ggml_tensor * node, int buffer_id, size_t offset) {
warning: llama-cpp-sys@0.0.1:             ^
warning: llama-cpp-sys@0.0.1: 1 warning generated.
warning: llama-cpp-sys@0.0.1: llama.cpp/ggml-backend.c:1167:13: warning: unused function 'ggml_backend_sched_print_assignments' [-Wunused-function]
warning: llama-cpp-sys@0.0.1: static void ggml_backend_sched_print_assignments(ggml_backend_sched_t sched, struct ggml_cgraph * graph) {
warning: llama-cpp-sys@0.0.1:             ^
warning: llama-cpp-sys@0.0.1: 1 warning generated.
warning: llama-cpp-sys@0.0.1: llama.cpp/ggml-quants.c:1447:14: warning: unused function 'make_qkx1_quants' [-Wunused-function]
warning: llama-cpp-sys@0.0.1: static float make_qkx1_quants(int n, int nmax, const float * restrict x, uint8_t * restrict L, float * restrict the_min,
warning: llama-cpp-sys@0.0.1:              ^
warning: llama-cpp-sys@0.0.1: llama.cpp/ggml-quants.c:11399:12: warning: unused function 'iq1_find_best_neighbour' [-Wunused-function]
warning: llama-cpp-sys@0.0.1: static int iq1_find_best_neighbour(const uint16_t * restrict neighbours, const uint64_t * restrict grid,
warning: llama-cpp-sys@0.0.1:            ^
warning: llama-cpp-sys@0.0.1: 2 warnings generated.
warning: llama-cpp-sys@0.0.1: llama.cpp/unicode.cpp:1413:20: warning: unused function 'unicode_cpts_to_utf8' [-Wunused-function]
warning: llama-cpp-sys@0.0.1: static std::string unicode_cpts_to_utf8(const std::vector<uint32_t> & cps) {
warning: llama-cpp-sys@0.0.1:                    ^
warning: llama-cpp-sys@0.0.1: llama.cpp/unicode.cpp:1458:30: warning: unused function 'unicode_cpt_to_utf16' [-Wunused-function]
warning: llama-cpp-sys@0.0.1: static std::vector<uint16_t> unicode_cpt_to_utf16(uint32_t cp) {
warning: llama-cpp-sys@0.0.1:                              ^
warning: llama-cpp-sys@0.0.1: llama.cpp/unicode.cpp:1482:17: warning: unused function 'cpt_from_utf16' [-Wunused-function]
warning: llama-cpp-sys@0.0.1: static uint32_t cpt_from_utf16(const std::vector<uint16_t> & utf16, size_t & offset) {
warning: llama-cpp-sys@0.0.1:                 ^
warning: llama-cpp-sys@0.0.1: 3 warnings generated.
    Finished release [optimized] target(s) in 0.08s
     Running `target/release/examples/basic`
llama_model_loader: loaded meta data with 24 key-value pairs and 291 tensors from models/mistral-7b-instruct-v0.2.Q5_K_M.gguf (version GGUF V3 (latest))
llama_model_loader: Dumping metadata keys/values. Note: KV overrides do not apply in this output.
llama_model_loader: - kv   0:                       general.architecture str              = llama
llama_model_loader: - kv   1:                               general.name str              = mistralai_mistral-7b-instruct-v0.2
llama_model_loader: - kv   2:                       llama.context_length u32              = 32768
llama_model_loader: - kv   3:                     llama.embedding_length u32              = 4096
llama_model_loader: - kv   4:                          llama.block_count u32              = 32
llama_model_loader: - kv   5:                  llama.feed_forward_length u32              = 14336
llama_model_loader: - kv   6:                 llama.rope.dimension_count u32              = 128
llama_model_loader: - kv   7:                 llama.attention.head_count u32              = 32
llama_model_loader: - kv   8:              llama.attention.head_count_kv u32              = 8
llama_model_loader: - kv   9:     llama.attention.layer_norm_rms_epsilon f32              = 0.000010
llama_model_loader: - kv  10:                       llama.rope.freq_base f32              = 1000000.000000
llama_model_loader: - kv  11:                          general.file_type u32              = 17
llama_model_loader: - kv  12:                       tokenizer.ggml.model str              = llama
llama_model_loader: - kv  13:                      tokenizer.ggml.tokens arr[str,32000]   = ["<unk>", "<s>", "</s>", "<0x00>", "<...
llama_model_loader: - kv  14:                      tokenizer.ggml.scores arr[f32,32000]   = [0.000000, 0.000000, 0.000000, 0.0000...
llama_model_loader: - kv  15:                  tokenizer.ggml.token_type arr[i32,32000]   = [2, 3, 3, 6, 6, 6, 6, 6, 6, 6, 6, 6, ...
llama_model_loader: - kv  16:                tokenizer.ggml.bos_token_id u32              = 1
llama_model_loader: - kv  17:                tokenizer.ggml.eos_token_id u32              = 2
llama_model_loader: - kv  18:            tokenizer.ggml.unknown_token_id u32              = 0
llama_model_loader: - kv  19:            tokenizer.ggml.padding_token_id u32              = 0
llama_model_loader: - kv  20:               tokenizer.ggml.add_bos_token bool             = true
llama_model_loader: - kv  21:               tokenizer.ggml.add_eos_token bool             = false
llama_model_loader: - kv  22:                    tokenizer.chat_template str              = {{ bos_token }}{% for message in mess...
llama_model_loader: - kv  23:               general.quantization_version u32              = 2
llama_model_loader: - type  f32:   65 tensors
llama_model_loader: - type q5_K:  193 tensors
llama_model_loader: - type q6_K:   33 tensors
llm_load_vocab: special tokens definition check successful ( 259/32000 ).
llm_load_print_meta: format           = GGUF V3 (latest)
llm_load_print_meta: arch             = llama
llm_load_print_meta: vocab type       = SPM
llm_load_print_meta: n_vocab          = 32000
llm_load_print_meta: n_merges         = 0
llm_load_print_meta: n_ctx_train      = 32768
llm_load_print_meta: n_embd           = 4096
llm_load_print_meta: n_head           = 32
llm_load_print_meta: n_head_kv        = 8
llm_load_print_meta: n_layer          = 32
llm_load_print_meta: n_rot            = 128
llm_load_print_meta: n_embd_head_k    = 128
llm_load_print_meta: n_embd_head_v    = 128
llm_load_print_meta: n_gqa            = 4
llm_load_print_meta: n_embd_k_gqa     = 1024
llm_load_print_meta: n_embd_v_gqa     = 1024
llm_load_print_meta: f_norm_eps       = 0.0e+00
llm_load_print_meta: f_norm_rms_eps   = 1.0e-05
llm_load_print_meta: f_clamp_kqv      = 0.0e+00
llm_load_print_meta: f_max_alibi_bias = 0.0e+00
llm_load_print_meta: n_ff             = 14336
llm_load_print_meta: n_expert         = 0
llm_load_print_meta: n_expert_used    = 0
llm_load_print_meta: causal attn      = 1
llm_load_print_meta: pooling type     = 0
llm_load_print_meta: rope type        = 0
llm_load_print_meta: rope scaling     = linear
llm_load_print_meta: freq_base_train  = 1000000.0
llm_load_print_meta: freq_scale_train = 1
llm_load_print_meta: n_yarn_orig_ctx  = 32768
llm_load_print_meta: rope_finetuned   = unknown
llm_load_print_meta: ssm_d_conv       = 0
llm_load_print_meta: ssm_d_inner      = 0
llm_load_print_meta: ssm_d_state      = 0
llm_load_print_meta: ssm_dt_rank      = 0
llm_load_print_meta: model type       = 7B
llm_load_print_meta: model ftype      = Q5_K - Medium
llm_load_print_meta: model params     = 7.24 B
llm_load_print_meta: model size       = 4.78 GiB (5.67 BPW)
llm_load_print_meta: general.name     = mistralai_mistral-7b-instruct-v0.2
llm_load_print_meta: BOS token        = 1 '<s>'
llm_load_print_meta: EOS token        = 2 '</s>'
llm_load_print_meta: UNK token        = 0 '<unk>'
llm_load_print_meta: PAD token        = 0 '<unk>'
llm_load_print_meta: LF token         = 13 '<0x0A>'
llm_load_tensors: ggml ctx size =    0.22 MiB
ggml_backend_metal_buffer_from_ptr: allocated buffer, size =  1478.14 MiB, ( 1478.22 / 49152.00)
llm_load_tensors: offloading 10 repeating layers to GPU
llm_load_tensors: offloaded 10/33 layers to GPU
llm_load_tensors:      Metal buffer size =  1478.14 MiB
llm_load_tensors:        CPU buffer size =  4892.99 MiB
..................................................................................................
llama_new_context_with_model: n_ctx      = 2048
llama_new_context_with_model: n_batch    = 2048
llama_new_context_with_model: n_ubatch   = 512
llama_new_context_with_model: freq_base  = 1000000.0
llama_new_context_with_model: freq_scale = 1
ggml_metal_init: allocating
ggml_metal_init: found device: Apple M3 Max
ggml_metal_init: picking default device: Apple M3 Max
ggml_metal_init: default.metallib not found, loading from source
ggml_metal_init: GGML_METAL_PATH_RESOURCES = nil
ggml_metal_init: error: could not use bundle path to find ggml-metal.metal, falling back to trying cwd
ggml_metal_init: loading 'ggml-metal.metal'
ggml_metal_init: error: Error Domain=MTLLibraryErrorDomain Code=3 "program_source:3:10: fatal error: 'ggml-common.h' file not found
#include "ggml-common.h"
         ^~~~~~~~~~~~~~~
" UserInfo={NSLocalizedDescription=program_source:3:10: fatal error: 'ggml-common.h' file not found
#include "ggml-common.h"
         ^~~~~~~~~~~~~~~
}
llama_new_context_with_model: failed to initialize Metal backend
thread 'main' panicked at examples/basic.rs:23:10:
called `Result::unwrap()` on an `Err` value: LlamaContextLoad(NullReturn)
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```
